export const CHANGE_LOGGED_IN = "CHANGE_LOGGED_IN";
export type CHANGE_LOGGED_IN = typeof CHANGE_LOGGED_IN;

export enum LoginActionType {
  LOGIN_STARTED = "LOGIN_STARTED",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_ERROR = "LOGIN_ERROR",
  LOGOUT = "LOGOUT"
}

export enum UsersActionType {
  FETCHING_USERS = "FETCHING_USERS",
  FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS",
  FETCHING_USERS_ERROR = "FETCHING_USERS_ERROR"
}
