export const CHANGE_LOGGED_IN = "CHANGE_LOGGED_IN";
export type CHANGE_LOGGED_IN = typeof CHANGE_LOGGED_IN;

export const FETCHING_USERS = "FETCHING_USERS";
export type FETCHING_USERS = typeof FETCHING_USERS;
export const FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS";
export type FETCHING_USERS_SUCCESS = typeof FETCHING_USERS_SUCCESS;
export const FETCHING_USERS_ERROR = "FETCHING_USERS_ERROR";
export type FETCHING_USERS_ERROR = typeof FETCHING_USERS_ERROR;
